### ISSUE TITLE
gitthub exclusions, and first running issues in MAIN

### ISSUE THREAD

**Issue by generrosity** [Phazorknight/Cogito#26] opened 2024-01-22 07:22 UTC
Hello!

Just downloading your MAIN and Experimental branches and they are quite different sizes!

The 6.4 meg of the COGITO folder is the same, but the .Godot folder has vast 'imported' (500M) and 'shadercache' (40M). The editor and export folder might also be not intentional 😁

I don'tt know how .gitignore works - and you have that folder listed there so ??????

**Comment by generrosity** [comment] 2024-01-22 07:45
Issues I encountered from the MAIN branch, incase you are interested;

- the referenced main scene is DEMO_01 rather than 01_DEMO
- Player rotation and torch ammo not reset
- 'Using' batteries from inventory turns on a pain field
- one instance of a rolling battery throwing the player like a skyrim doll, and then ... doing a forward roll on landing I think?

Very excited checking everything out!

**Comment by Phazorknight** [comment] 2024-01-22 17:54
Hey, thanks for these flags.

**Re github ignores:** Yeah, for some reason GitHub Desktop regularly tries to sneak in the .godot folder in my commits.
Once you have the input_helper and quick_audio addons, it is save to just download the /COGITO/ dir as everything is contained in there.
Also it's recommended to stick to main branch, everything's been moved over into main for now.

**Menu main scene reference:** Thanks for flagging this, will be fixed in **BETA 202401.11** coming later today.

**Player rotation and torch ammo not reset:** Not completely sure I understand what you mean. The ammo/charge of wieldables like the flashlight is currently not being properly saved/loaded when using saves or scene transitions, so it will behave unexpectedly.

**Using batteries turns on pain field:** Wasn't able to reproduce this. Could you provide more information? Did you use the batteries from inventory or by trying to reload the flashlight? Which buttons did you press? Did you load a save or transition from a different scene before you used the battery? Did just the damage indicator turn on and off or did the player actually take damage?

**Rolling battery throwing the player:** This is just a case of fun video game physics. Tweaking collision shapes and RigidBody3D settings might help with avoiding this a bit. The roll on landing is part of the Player Controller that gets triggered when falling from a certain height and having a certain speed.

**Comment by generrosity** [comment] 2024-01-22 22:32
Thanks for all the confirmations!

Off memory;
- start game, move around, return to main menu, start game, player facing the wall
- hover over the inventory item for battery and use it several times. Seemed to be consistant after cycling through main menu.

I'll reconfirm tomorrow night from a fresh start incase these were glitched in some other way.

Thanks!

**Comment by generrosity** [comment] 2024-01-24 08:44
Thanks again for your work 💚

* Deleted and Re-downloaded fresh into the same directory.


* Following warnings on first time loading, but doesn't stop the game from loading.
![image](https://github.com/Phazorknight/Cogito/assets/12838061/b1f1c4a8-6f26-4ec4-a99f-7348f66b744b)

* Have you reversed the "invert Y axis"? Or has the previous saved settings swapped it to be opposite to what it was maybe?

* If you have no stamina, you don't move at all. Just by jumping around a lot.

* No kill zone under the platform if you fall off 😁

* There are a couple of places with texture z-fighting like the scene transition doorway and the chest lid (visible in editor). Sorry I don't know much about geometry and if other "material" settings could fix that, but hiding either surface texture didn't help.
![image](https://github.com/Phazorknight/Cogito/assets/12838061/b48758f6-cc7b-4e31-b13b-b1b4bb5a03e4)


* Confirmed the situation where the Player rotatiton occurs.
1: Open game - Start - looking at 'Welcome' ✅
1: Open game - Start - Back to Main Menu - Start - looking at 'Welcome' ✅
1: Open game - Start - walk into transition zone - Back to Main Menu - Start - looking into the transition zone ⁉
1: Open game - Start - walk into transition zone - walk back to main zone (end up facing and located correctly) - Back to Main Menu - Start - standing in the gun room, looking at the wall ❌
1: Open game - Start - walk into transition zone - walk back to main zone BACKWARDS - Back to Main Menu - Start - standing in the gun room, looking into the room (ie remembered the degree angle turn)❌

**Comment by Phazorknight** [comment] 2024-01-24 21:31
> Following warnings on first time loading, but doesn't stop the game from loading.
Ran this on a fresh install and had the same. But as you said everything seems to be working correctly. I kinda suspect this has to do with the Autoloads being set, but not 100% sure.

> Have you reversed the "invert Y axis"? Or has the previous saved settings swapped it to be opposite to what it was maybe?
Not sure I understand what the issue is? Works as expected on my end. Invert Y axis can be set via the options and gets saved with the config. Per default it is on.

> If you have no stamina, you don't move at all. Just by jumping around a lot.
Could not reproduce, but the Stamina component had a small bug in it that I fixed this morning. Expected behaviour is that when player is sprinting and then runs out of stamina, player speed gets reduced to walking speed. Player is unable to sprint or jump while stamina is 0.

> Confirmed the situation where the Player rotatiton occurs.
I was able to reproduce the ones when going back to the Main Menu and then pressing start game (the three cases you list are bascially all the same issue). Have a decent idea on how to fix it and will look into it.

> texture z-fighting
Just proof of me being bad at creating assets. Will fix/update when I have some time for it.

> No kill zone under the platform if you fall off 😁
Not a bug, but was thinking of adding one already anyway. Will fix/update when I have some time for it.

**Comment by generrosity** [comment] 2024-01-25 04:55
Very nice!

I can definitely hold down forward, hold down shift, hold down space, be bouncing around, and then come to a completely (if wobbly) stop. Without the sprint, I wait and hop, Kill zone works great 😁👌

Feel free to close this off if you have things otherwise tracked :) its great stuff.

**Comment by Phazorknight** [comment] 2024-01-25 17:32
Sweet.
Cheers mate.

**Closed by Phazorknight** 2024-01-25 17:32 UTC
