### ISSUE TITLE
Gamepad, Player Inventory: Unable to "Use" wieldables or combinables

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#239] opened 2024-08-02 06:35 UTC
**Cogito and Godot Engine Version:**
Cogito version: beta 202407.01, Godot version: 4.2.2stable

**Description:**
Using a gamepad in the player inventory, when the selected inventory slot is a wieldable item or when attempting to combine combinables, pressing the use button (Joypad Button 0, "inventory_use_item"). It only triggers the generic error sound.

**Reproduction steps:**
Requires a gamepad (in my case, a DualShock)

For wieldables:
1. Pick up the flashlight
2. Open the player inventory
3. Try to use the flashlight (Joypad Button 0)
   - Using a mouse, this input action will toggle the wielded state of the flashlight

For combinables:
1. Pick up both page A and page B
2. Open the player inventory
3. Move page B over to the slot holding page A
4. Try to use page B on the slot holding page A

**Expected behavior:**
When using a gamepad and selecting the flashlight slot in player inventory, pressing the input action "inventory_use_item" will toggle the wielded state of the flashlight, just like it does when clicking the right mouse button

When using a gamepad and attempting to combine the two pages, pressing the input action "inventory_use_item" will combine the pages, just like it does when clicking the right mouse button

**Comment by Phazorknight** [comment] 2024-08-02 16:08
Thanks for reporting this.

*Re Wieldables:*
I wasn't able to reproduce this. When picking up the flashlight, selecting it in the inventory and pressing the `use` button on the gamepad, it gets equipped/unequipped, which is the expected behavior. Will look into it though.

*Re combinables*:
Yeah, was able to reproduce this issue (and another one where I was able to "delete" one page while dropping the other, so not good 😓 ). Will look into fixing this.

**Comment by Phazorknight** [comment] 2024-08-02 16:39
*Re Wieldables:*
Actually, i think I was now able tor reproduce that one too. Looking into this more.

**Comment by Phazorknight** [comment] 2024-08-02 17:20
@PeterD23 might need your help on this one.

I think both these errors have to do with how the grid inventory populates/re-populates the slots when items get moved around.
When an item first gets added to the inventory, the gamepad use_item buttons on it work, but as soon as items get moved around, they break, so I assume there's some kind of slot index error happening.

**Comment by PeterD23** [comment] 2024-08-03 19:12
Yeah I can potentially look into it. Apologies for my inactivity as I've a number of health related obstacles currently but I'll look into the code over the new few days and see if I can figure out a fix

**Comment by Phazorknight** [comment] 2024-08-04 01:10
@PeterD23 no apologies needed, COGITO isn't a "day job". Hope your health obstacles can be overcome soon!

I've added a few print statements in the latest pull to trace a bit where the inventory slot disconnect happens, but a lot of them don't even get reached... I don't think I can look into this more this weekend.

**Comment by PeterD23** [comment] 2024-08-05 17:53
So I put a breakpoint against all the Audio emitters to see which one was triggering the error, and it appears to be check_entered_code which is part of cogito_keypad.gd:131. For whatever reason the use button seems to think that its interacting with a keypad when you use the flashlight.

**Comment by Phazorknight** [comment] 2024-08-05 23:54
@PeterD23 thanks for this! The keypad was actually the reason this caused issues.
The Cogito UI buttons would handle input events and send them to the keypad. (this also meant this issue would actually not occur if you were playtesting a scene with no keypad in it).

I've added some checks in https://github.com/Phazorknight/Cogito/commit/ed83c1327773f7d13c6a804b4b0bfe124350f719 and so far this seems to have resolved the issue.

@OvercastInteractive please try the commit mentioned above and let me know if you're still running into any issues.

**Comment by PeterD23** [comment] 2024-08-06 01:04
No worries! I was trying to figure out a fix but I think I need to learn more about signal handling in UI's, although looking at your commit that seemed to be the solution I was thinking of but wasn't sure where it needed to go 😅 If the combinables is still having issues I can take a look at it, since I'm not 100% sure if I fully tested it with the gamepad.

**Comment by Phazorknight** [comment] 2024-09-03 16:24
Closing, assuming this is resolved.

**Closed by Phazorknight** 2024-09-03 16:24 UTC
Labels: bug
