### ISSUE TITLE
Enemy, Script: Patrol points not added on scene enter

### ISSUE THREAD

**Issue by OvercastInteractive** [Phazorknight/Cogito#264] opened 2024-09-10 04:08 UTC
**Cogito and Godot Engine Version:**
Godot: 4.2.2
Cogito: beta 202409.02

**Description:**
Saving in the Lobby before entering the Laboratory breaks the enemy's patrol points.

**Reproduction steps:**
1. Start a new game
2. Save in the Lobby
3. Enter the Laboratory
- Should get an index out of bounds exception

**Expected behavior:**
Enemy patrol points are saved or unaffected by scene changes.

**Screenshots:**
![Cogito_Enemy_Patrol_Points_Issue_01](https://github.com/user-attachments/assets/663c7931-6eed-410c-8b5c-87aed2049e29)

**Comment by Phazorknight** [comment] 2024-09-10 19:15
I've added some code to at least prevent crashes when transitioning to level scenes with enemies in them, see https://github.com/Phazorknight/Cogito/commit/5182d7ad93e02ed3ff3b4beafbb2bc089e3082f4

Will look into this more but for now at least this prevents crashes.

**Comment by Phazorknight** [comment] 2024-09-10 22:54
Okay, I've changed the implementation of patrolling a bit to make this work in https://github.com/Phazorknight/Cogito/commit/e96be850e44fe03654708a61f507019b598e87b0:

There's now a script that can be attached to a node called `cogito_patrol_path.gd` which holds the Node3D Array to the patrol points.
You can set a reference to a cogito_patrol_path in your enemy's inspector and this reference is saved and loaded as expected.

@OvercastInteractive pls let me know if this resolves this issue for you.

**Comment by OvercastInteractive** [comment] 2024-09-11 01:26
I'm seeing a different issue now, the patrol_points array isn't getting initialized on load so it throws an error when attempting to get the array's size. 

![Cogito_Enemy_Patrol_Points_Issue_02](https://github.com/user-attachments/assets/ae8155c7-c508-4c11-af40-5edd60a010be)

My basic workaround just assumes all the patrol points are children of the patrol path node and are added on ready:
![Cogito_Enemy_Patrol_Points_Issue_03](https://github.com/user-attachments/assets/dc4a9a3a-da82-4aa7-83fe-d1395c3697be)

**Comment by Phazorknight** [comment] 2024-09-11 01:38
Oh that's really odd. When exactly does this error happen? On testing the level scene directly? or when/after transitioning?

As the CogitoPatrolPath node is part of the level scene, it should always be available before the enemy gets loaded... 

I personally don't want to dynamically add the patrol points to the array as I want to be able to re-use points between different paths and also leave it open to change their order within the array.

**Comment by Phazorknight** [comment] 2024-09-12 15:19
@OvercastInteractive thanks for this. I've realized that this issue is caused by the order in which godot loads nodes/scripts.

Please see https://github.com/Phazorknight/Cogito/commit/6c396f598a83ce757492510e9302c123a4fd5a7b for my attempt to fix this and hopefully improve robustness to the enemy script in general.

**Comment by OvercastInteractive** [comment] 2024-09-13 01:18
Good to know, I've come across similar cases in my own projects in regard to script call order.
Your changes look to have fixed this issue, thanks!

**Comment by Phazorknight** [comment] 2024-09-13 01:49
Awesome, closing this.

**Closed by Phazorknight** 2024-09-13 01:49 UTC
Labels: bug
